function [linePointer, dataStr]=printTerminal(dataStr,dataIn,lineNum,GuiHandle)
handles = guidata(GuiHandle);

if lineNum>15
    lineNum=15;
    dataStr{1}=dataStr{2};
    dataStr{2}=dataStr{3};
    dataStr{3}=dataStr{4};
    dataStr{4}=dataStr{5};
    dataStr{5}=dataStr{6};
    dataStr{6}=dataStr{7};
    dataStr{7}=dataStr{8};
    dataStr{8}=dataStr{9};
    dataStr{9}=dataStr{10};
    dataStr{10}=dataStr{11};
    dataStr{11}=dataStr{12};
    dataStr{12}=dataStr{13};
    dataStr{13}=dataStr{14};
    dataStr{14}=dataStr{15};
    dataStr{lineNum}=dataIn;
    dataStr{lineNum+1}='>>_';
else
    dataStr{lineNum}=dataIn;
    dataStr{lineNum+1}='>>_';
end                            

set(handles.consola, 'String', [dataStr{1},char(10),...
                                    dataStr{2},char(10),...
                                    dataStr{3},char(10),...
                                    dataStr{4},char(10),...
                                    dataStr{5},char(10),...
                                    dataStr{6},char(10),...
                                    dataStr{7},char(10),...
                                    dataStr{8},char(10),...
                                    dataStr{9},char(10),...
                                    dataStr{10},char(10),...
                                    dataStr{11},char(10),...
                                    dataStr{12},char(10),...
                                    dataStr{13},char(10),...
                                    dataStr{14},char(10),...
                                    dataStr{15},char(10),...
                                    dataStr{16}]);
                                
                                linePointer=lineNum+1;
                                

end